### ISSUE TITLE
keyfile for floodgate can not be found

### ISSUE THREAD

**Issue by MrGeorgen** [GeyserMC/Geyser-Fabric#12]
```
[13:19:35] [Network Listener - #1/INFO]: Player connected with username MCbos31YT
[13:19:42] [Network Listener - #1/INFO]: Attempting to login using floodgate mode... authentication will be encrypted.
[13:19:42] [Thread-90/INFO]: [STDERR]: java.lang.NullPointerException
[13:19:42] [Thread-90/INFO]: [STDERR]:  at java.base/java.nio.file.Files.provider(Files.java:100)
[13:19:42] [Thread-90/INFO]: [STDERR]:  at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
[13:19:42] [Thread-90/INFO]: [STDERR]:  at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
[13:19:42] [Thread-90/INFO]: [STDERR]:  at java.base/java.nio.file.Files.readAllBytes(Files.java:3205)
[13:19:42] [Thread-90/INFO]: [STDERR]:  at org.geysermc.floodgate.util.EncryptionUtil.getKeyFromFile(EncryptionUtil.java:92)
[13:19:42] [Thread-90/INFO]: [STDERR]:  at org.geysermc.connector.network.session.GeyserSession.connectDownstream(GeyserSession.java:665)
[13:19:42] [Thread-90/INFO]: [STDERR]:  at org.geysermc.connector.network.session.GeyserSession.lambda$authenticate$2(GeyserSession.java:589)
[13:19:42] [Thread-90/INFO]: [STDERR]:  at java.base/java.lang.Thread.run(Thread.java:834)
[13:20:02] [Network Listener - #1/INFO]: Bedrock user with ip: /80.208.184.247 has disconnected for reason CLOSED_BY_REMOTE_PEER
```
where should I put the public keyfile? I tried config/floodgate/public-key.pem and
config/Geyser-Fabric/public-key.pem

**Comment by MrGeorgen** [comment]
I didn't use floodgate 2
