### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by WNCX** [GeyserMC/Geyser-Fabric#25]
I just installed the latest version of the geyser - fabric and fabric API and then imported the old save from version 1.16.5, and then the server crashed, is there a problem with my save？ If so, what should I do with this save? This save has been with us for half a year and there's still a lot to do.

This is crash-report:
```
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 7/23/21, 10:51 AM
Description: Exception in server tick loop

java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.LinkedHashMap.newNode(LinkedHashMap.java:257)
	at java.base/java.util.HashMap.putVal(HashMap.java:631)
	at java.base/java.util.HashMap.put(HashMap.java:612)
	at com.nukkitx.nbt.NBTInputStream.deserialize(NBTInputStream.java:69)
	at com.nukkitx.nbt.NBTInputStream.deserialize(NBTInputStream.java:78)
	at com.nukkitx.nbt.NBTInputStream.deserialize(NBTInputStream.java:69)
	at com.nukkitx.nbt.NBTInputStream.readTag(NBTInputStream.java:33)
	at com.nukkitx.nbt.NBTInputStream.readTag(NBTInputStream.java:22)
	at org.geysermc.connector.registry.populator.BlockRegistryPopulator.registerBedrockBlocks(BlockRegistryPopulator.java:111)
	at org.geysermc.connector.registry.populator.BlockRegistryPopulator.populate(BlockRegistryPopulator.java:101)
	at org.geysermc.connector.registry.BlockRegistries.<clinit>(BlockRegistries.java:70)
	at org.geysermc.connector.GeyserConnector.<init>(GeyserConnector.java:152)
	at org.geysermc.connector.GeyserConnector.start(GeyserConnector.java:488)
	at org.geysermc.platform.fabric.GeyserFabricMod.startGeyser(GeyserFabricMod.java:159)
	at org.geysermc.platform.fabric.GeyserFabricMod$$Lambda$2869/0x00000008013b2070.onServerStarted(Unknown Source)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:48)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents$$Lambda$2842/0x0000000801337210.onServerStarted(Unknown Source)
	at net.minecraft.server.MinecraftServer.handler$zzc000$afterSetupServer(MinecraftServer.java:1807)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at net.minecraft.server.MinecraftServer$$Lambda$4115/0x00000008014fa248.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 4.18.0-193.28.1.el8_2.x86_64
	Java Version: 16.0.1, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Red Hat, Inc.
	Memory: 3235400 bytes (3 MiB) / 464257024 bytes (442 MiB) up to 464257024 bytes (442 MiB)
	CPUs: 1
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) Gold 6133 CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 1
	Graphics card #0 name: GD 5446
	Graphics card #0 vendor: Cirrus Logic (0x1013)
	Graphics card #0 VRAM (MB): 32.00
	Graphics card #0 deviceId: 0x00b8
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): -0.00
	Memory slot #0 type: RAM
	Virtual memory max (MB): 913.49
	Virtual memory used (MB): 983.03
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 0 total; 
	Fabric Mods: 
		fabric: Fabric API 0.37.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57718
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab612118
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57718
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		geyser-fabric: Geyser-Fabric 1.4.0-SNAPSHOT
		java: OpenJDK 64-Bit Server VM 16
		minecraft: Minecraft 1.17.1
	Player Count: 0 / 20; []
	Data Packs: vanilla, file/craft (incompatible), Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Konicai** [comment]
I can't tell if your max ram is ~440MB or ~900M, but regardless, neither of those are enough to run a 1.17.1 server. As far as I understand Geyser needs a fairly significant amount of memory to initially load the necessary translation data

**Comment by Infinity-Ad973** [comment]
OutOfMemoryError,plz check ur mamory.

**Comment by WNCX** [comment]
> I can't tell if your max ram is ~440MB or ~900M, but regardless, neither of those are enough to run a 1.17.1 server. As far as I understand Geyser needs a fairly significant amount of memory to initially load the necessary translation data

Thank you for your answer 
I just tried the specified memory capacity, now solved, thank you very much
