### ISSUE TITLE
Geyser-fabric (and floodgate) crash on startup

### ISSUE THREAD

**Issue by warior456** [GeyserMC/Geyser-Fabric#50]
With Geyser-fabric or/and floodgate my server wont start up

geyser only: https://mcpaste.io/71b4b06255bb79df
geyser and floodgate: https://mcpaste.io/56acf38f36707d9f
floodgate only: https://mcpaste.io/bc1865f787fc905d
running latest floodgate and latest geyser-fabric

**Comment by warior456** [comment]
after running all these (even without other mods) not a single config file generated

**Comment by pwnker** [comment]
I am seeing similar errors.

**Comment by Camotoy** [comment]
Use https://ci.opencollab.dev/job/GeyserMC/job/Floodgate-Fabric/job/master/70/, which is the latest build but may not show up as the latest build. We'll fix this.

**Comment by pwnker** [comment]
```java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'geyser-fabric'!
mc_1  | 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.5.jar:?]
mc_1  | 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.5.jar:?]
mc_1  | 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.5.jar:?]
mc_1  | 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.5.jar:?]
mc_1  | 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.5.jar:?]
mc_1  | 	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
mc_1  | 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.5.jar:?]
mc_1  | 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.5.jar:?]
mc_1  | 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.5.jar:?]
mc_1  | 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.5.jar:?]
mc_1  | 	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:64) [fabric-server-mc.1.18.2-loader.0.14.5-launcher.0.10.2.jar:0.10.2]
mc_1  | Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because the return value of "org.geysermc.geyser.GeyserBootstrap.getConfigFolder()" is null
mc_1  | 	at org.geysermc.geyser.text.GeyserLocale.loadGeyserLocale(GeyserLocale.java:122) ~[Geyser-Fabric-2.0.3-SNAPSHOT.jar:?]
mc_1  | 	at org.geysermc.geyser.text.GeyserLocale.init(GeyserLocale.java:59) ~[Geyser-Fabric-2.0.3-SNAPSHOT.jar:?]
mc_1  | 	at org.geysermc.platform.fabric.GeyserFabricMod.onEnable(GeyserFabricMod.java:100) ~[Geyser-Fabric-2.0.3-SNAPSHOT.jar:?]
mc_1  | 	at org.geysermc.platform.fabric.GeyserFabricMod.onInitialize(GeyserFabricMod.java:91) ~[Geyser-Fabric-2.0.3-SNAPSHOT.jar:?]
mc_1  | 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.5.jar:?]
mc_1  | 	... 8 more
``` Geyser still shows this error when using the actual latest floodgate and geyser builds

**Comment by Claw256** [comment]
I am also getting similar errors to @pwnker, even after the using the build suggested by @Camotoy. Here is my log snippet: 
```
[17:16:12] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/container/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[17:16:12] [main/INFO]: Compatibility level set to JAVA_16
[17:16:12] [main/INFO]: Compatibility level set to JAVA_17
[17:16:12] [main/INFO]: Loaded configuration file for Lithium: 100 options available, 3 override(s) found
[17:16:13] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[17:16:13] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [servercore]) disables it and children
[17:16:13] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton, vmp]) disables it and children
[17:16:13] [main/INFO]: Smooth Boot config initialized
[17:16:14] [main/WARN]: Method overwrite conflict for method_18472 in observable.common.json:LevelMixin from mod observable, previously written by dev.the_fireplace.eer.mixin.WorldMixin. Skipping method.
[17:16:14] [main/WARN]: Method overwrite conflict for method_5800 in carpet-fixes.mixins.json:itemFixes.ItemEntity_lightningKillsDropsMixin from mod carpet-fixes, previously written by carpet.mixins.ItemEntityMixin. Skipping method.
[17:16:16] [main/WARN]: @ModifyConstant conflict. Skipping servercore.mixins.json:features.misc.MinecraftServerMixin from mod servercore->@ModifyConstant::modifyAutoSaveInterval(I)I with priority 900, already redirected by carpet-fixes.mixins.json:advanced.MinecraftServer_autosaveDelayMixin from mod carpet-fixes->@ModifyConstant::tickAutoSave(I)I with priority 1000
[17:16:17] [main/INFO]: Compression will use libdeflate (Linux x86_64), encryption will use OpenSSL 1.1.x (Linux x86_64)
[17:16:17] [main/INFO]: Registering class observable.net.BetterChannel$PartialPacketBegin
[17:16:17] [main/INFO]: Registered class observable.net.BetterChannel$PartialPacketBegin
[17:16:17] [main/INFO]: Registering class observable.net.BetterChannel$PartialPacketData
[17:16:17] [main/INFO]: Registered class observable.net.BetterChannel$PartialPacketData
[17:16:17] [main/INFO]: Registering class observable.net.C2SPacket$InitTPSProfile
[17:16:17] [main/INFO]: Registered class observable.net.C2SPacket$InitTPSProfile
[17:16:17] [main/INFO]: Registering class observable.net.C2SPacket$RequestTeleport
[17:16:17] [main/INFO]: Registered class observable.net.C2SPacket$RequestTeleport
[17:16:17] [main/INFO]: Registering class observable.net.C2SPacket$RequestAvailability
[17:16:17] [main/INFO]: Registered class observable.net.C2SPacket$RequestAvailability
[17:16:17] [main/INFO]: Registering class observable.net.S2CPacket$ProfilingStarted
[17:16:17] [main/INFO]: Registered class observable.net.S2CPacket$ProfilingStarted
[17:16:17] [main/INFO]: Registering class observable.net.S2CPacket$ProfilingCompleted
[17:16:17] [main/INFO]: Registered class observable.net.S2CPacket$ProfilingCompleted
[17:16:17] [main/INFO]: Registering class observable.net.S2CPacket$ProfilerInactive
[17:16:17] [main/INFO]: Registered class observable.net.S2CPacket$ProfilerInactive
[17:16:17] [main/INFO]: Registering class observable.net.S2CPacket$ProfilingResult
[17:16:17] [main/INFO]: Registered class observable.net.S2CPacket$ProfilingResult
[17:16:17] [main/INFO]: Registering class observable.net.S2CPacket$Availability
[17:16:17] [main/INFO]: Registered class observable.net.S2CPacket$Availability
[17:16:17] [main/INFO]: Registering class observable.net.S2CPacket$ConsiderProfiling
[17:16:17] [main/INFO]: Registered class observable.net.S2CPacket$ConsiderProfiling
[17:16:17] [main/INFO]: [ServerCore] Initializing...
[17:16:17] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'geyser-fabric'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.5.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.5.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because the return value of "org.geysermc.geyser.GeyserBootstrap.getConfigFolder()" is null
	at org.geysermc.geyser.text.GeyserLocale.loadGeyserLocale(GeyserLocale.java:122) ~[Geyser-Fabric-2.0.3-SNAPSHOT.jar:?]
	at org.geysermc.geyser.text.GeyserLocale.init(GeyserLocale.java:59) ~[Geyser-Fabric-2.0.3-SNAPSHOT.jar:?]
	at org.geysermc.platform.fabric.GeyserFabricMod.onEnable(GeyserFabricMod.java:100) ~[Geyser-Fabric-2.0.3-SNAPSHOT.jar:?]
	at org.geysermc.platform.fabric.GeyserFabricMod.onInitialize(GeyserFabricMod.java:91) ~[Geyser-Fabric-2.0.3-SNAPSHOT.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.5.jar:?]
	... 7 more

```
I think this is a Geyser-Fabric issue.

**Comment by pwnker** [comment]
No problem thanks for the quick response.

**Comment by Claw256** [comment]
Perfect, thanks again for the responce.

**Comment by Camotoy** [comment]
The next Geyser-Fabric build should resolve this.

**Comment by warior456** [comment]
is floodgate supposed to launch without geyser installed?
