### ISSUE TITLE
Server doesnt close correcly with geyser and floodgate installed on a fabric server

### ISSUE THREAD

**Issue by sussyboiiii** [GeyserMC/Geyser-Fabric#58]

**Comment by DerpyPlayz18** [comment]
Having the same issue.
Dump: https://dump.geysermc.org/mPL0tGG63FgvRvGE7boZWs1SDyAvdoVB

Logs:
`[16:22:22] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.6
[16:22:23] [ForkJoinPool-1-worker-1/WARN]: Mod com_github_shevek_parallelgzip uses the version af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[16:22:23] [main/WARN]: Warnings were found!
 - Mod 'Textile Backup' (textile_backup) 2.3.1-1.19 recommends any version of modmenu, which is missing!
	 - You should install any version of modmenu for the optimal experience.
[16:22:23] [main/INFO]: Loading 66 mods:
	- adventure-platform-fabric 5.4.0-SNAPSHOT via floodgate
	- carpet 1.4.79
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.65
	- cloud 1.7.0-SNAPSHOT via floodgate
	- cloud_commandframework_cloud-brigadier_ 1.7.0-SNAPSHOT via cloud
	- cloud_commandframework_cloud-core_ 1.7.0-SNAPSHOT via cloud
	- cloud_commandframework_cloud-services_ 1.7.0-SNAPSHOT via cloud
	- com_github_shevek_parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6 via textile_backup
	- fabric 0.55.2+1.19
	- fabric-api-base 0.4.8+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.5+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.11+e62f51a3a9 via fabric
	- fabric-command-api-v1 1.2.4+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.0+cda9839ba9 via fabric
	- fabric-commands-v0 0.2.21+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.26+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.0.15+9ff28f40a9 via fabric
	- fabric-convention-tags-v1 1.0.7+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.2+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.0.0+2a5b9210a9 via fabric
	- fabric-dimensions-v1 2.1.26+72da3b3da9 via fabric
	- fabric-entity-events-v1 1.4.15+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.25+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.23+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.18+18990361a9 via fabric
	- fabric-item-api-v1 1.5.3+767db26ea9 via fabric
	- fabric-item-groups-v0 0.3.22+9ff28f40a9 via fabric
	- fabric-lifecycle-events-v1 2.0.8+21a5acaaa9 via fabric
	- fabric-loot-api-v2 1.0.0+9e7660c6a9 via fabric
	- fabric-loot-tables-v1 1.1.0+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.0+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.6+9ff28f40a9 via fabric
	- fabric-networking-api-v1 1.0.26+7fe97409a9 via fabric
	- fabric-networking-v0 0.3.13+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.4+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.7+9ff28f40a9 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via cloud
	- fabric-registry-sync-v0 0.9.15+92cf9a3ea9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.11+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.4+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.8+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.2+9e7660c6a9 via fabric
	- fabric-screen-handler-api-v1 1.2.5+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.7+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.0+9e7660c6a9 via fabric
	- fabricloader 0.14.6
	- floodgate 2.2.0-SNAPSHOT
	- geyser-fabric 2.0.5-SNAPSHOT
	- io_leangen_geantyref_geantyref 1.3.13 via cloud
	- java 17
	- lithium 0.8.0
	- minecraft 1.19
	- net_kyori_adventure-api 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-key 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-platform-api 4.1.0 via adventure-platform-fabric
	- net_kyori_adventure-text-logger-slf4j 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-minimessage 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-gson 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-plain 4.11.0 via adventure-platform-fabric
	- net_kyori_examination-api 1.3.0 via adventure-platform-fabric
	- net_kyori_examination-string 1.3.0 via adventure-platform-fabric
	- org_apache_commons_commons-compress 1.19 via textile_backup
	- org_tukaani_xz 1.9 via textile_backup
	- phosphor 0.8.1
	- textile_backup 2.3.1-1.19
[16:22:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/tramo/OneDrive/Desktop/Stuff/Server/Napogatto/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[16:22:23] [main/INFO]: Compatibility level set to JAVA_17
[16:22:24] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 0 override(s) found
[16:22:40] [main/INFO]: Building unoptimized datafixer
[16:22:50] [main/INFO]: [Textile Backup] Starting Textile Backup by Szum123321
[16:22:50] [Thread-1/WARN]: 
**********************************
* You specified an empty prefix in your Floodgate config for Bedrock players!
* Should a Java player join and a Bedrock player join with the same username, unwanted results and conflicts will happen!
* We strongly recommend using . as the prefix, but other alternatives that will not conflict include: +, - and *
**********************************
[16:22:51] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:22:56] [main/INFO]: Loaded 7 recipes
[16:22:57] [main/INFO]: Loaded 1179 advancements
[16:22:59] [main/INFO]: Applied 0 biome modifications to 0 of 63 new biomes in 5.044 ms
[16:22:59] [Server thread/INFO]: Starting minecraft server version 1.19
[16:22:59] [Server thread/INFO]: Loading properties
[16:22:59] [Server thread/INFO]: Default game type: SURVIVAL
[16:22:59] [Server thread/INFO]: Generating keypair
[16:23:00] [Server thread/INFO]: Starting Minecraft server on *:25565
[16:23:00] [Server thread/INFO]: Using default channel type
[16:23:00] [Server thread/INFO]: Preparing level "world"
[16:23:00] [Server thread/INFO]: [CM]: loaded setting lagFreeSpawning as true from carpet.conf
[16:23:01] [Server thread/INFO]: [CM]: loaded setting maxEntityCollisions as 5 from carpet.conf
[16:23:02] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[16:23:14] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-7/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-7/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-7/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[16:23:14] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[16:23:15] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[16:23:15] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[16:23:16] [Worker-Main-6/INFO]: Preparing spawn area: 1%
[16:23:16] [Worker-Main-5/INFO]: Preparing spawn area: 18%
[16:23:17] [Worker-Main-7/INFO]: Preparing spawn area: 58%
[16:23:17] [Server thread/INFO]: Time elapsed: 15360 ms
[16:23:17] [Server thread/INFO]: Done (16.730s)! For help, type "help"
[16:23:17] [Server thread/INFO]: Took 65ms to boot Floodgate
[16:23:17] [Server thread/INFO]: ******************************************
[16:23:17] [Server thread/INFO]: 
[16:23:17] [Server thread/INFO]: Loading Geyser version 2.0.5-SNAPSHOT (git-0efd04dd87183064f51de93bc93b7058aeec9b69-0efd04d)
[16:23:17] [Server thread/INFO]: 
[16:23:17] [Server thread/INFO]: ******************************************
[16:23:19] [Thread-7/WARN]: 
**********************************
* You specified an empty prefix in your Floodgate config for Bedrock players!
* Should a Java player join and a Bedrock player join with the same username, unwanted results and conflicts will happen!
* We strongly recommend using . as the prefix, but other alternatives that will not conflict include: +, - and *
**********************************
[16:23:25] [Network Listener - #1/INFO]: Started Geyser on 0.0.0.0:19132
[16:23:25] [Server thread/INFO]: Done (7,69s)! Run /geyser help for help!
[16:23:25] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 7911ms or 158 ticks behind
[16:23:35] [ForkJoinPool.commonPool-worker-1/ERROR]: Failed to load locale asset cache: Unrecognized token 'Read': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"Read timed out"; line: 1, column: 5]
[16:23:35] [ForkJoinPool.commonPool-worker-1/INFO]: Downloading Minecraft JAR to extract en_us locale, please wait... (this may take some time depending on the speed of your internet connection)
[16:23:35] [ForkJoinPool.commonPool-worker-1/ERROR]: Unable to download and extract en_us locale!
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.text.MinecraftLocale$VersionDownload.getUrl()" because "org.geysermc.geyser.text.MinecraftLocale.clientJarInfo" is null
	at org.geysermc.geyser.text.MinecraftLocale.downloadEN_US(MinecraftLocale.java:266) ~[Geyser-Fabric.jar:?]
	at org.geysermc.geyser.text.MinecraftLocale.downloadLocale(MinecraftLocale.java:189) ~[Geyser-Fabric.jar:?]
	at org.geysermc.geyser.text.MinecraftLocale.downloadAndLoadLocale(MinecraftLocale.java:139) ~[Geyser-Fabric.jar:?]
	at org.geysermc.geyser.text.MinecraftLocale.lambda$static$0(MinecraftLocale.java:59) ~[Geyser-Fabric.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) [?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) [?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[16:23:35] [ForkJoinPool.commonPool-worker-1/WARN]: Missing MC locale file: en_us
[16:23:42] [Server thread/INFO]: Collecting dump info[0m
[16:23:43] [Server thread/INFO]: Uploading dump[0m
[16:23:43] [Server thread/INFO]: We've made a dump with useful information, report your issue and provide this url: [0;36mhttps://dump.geysermc.org/mPL0tGG63FgvRvGE7boZWs1SDyAvdoVB[0m
[16:24:18] [Server thread/INFO]: Stopping the server
[16:24:18] [Server thread/INFO]: Shutting down Geyser.
[16:24:18] [Server thread/INFO]: Geyser shutdown successfully.
[16:24:18] [Server thread/INFO]: Stopping server
[16:24:18] [Server thread/INFO]: Saving players
[16:24:18] [Server thread/INFO]: Saving worlds
[16:24:18] [WebSocketConnectReadThread-62/INFO]: The skin uploader has been closed
[16:24:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[16:24:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[16:24:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[16:24:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[16:24:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[16:24:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[16:24:20] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
`

After that it just gets stuck like this and nothing else happens

**Comment by smounives** [comment]
I have the same issue here.

**Comment by onebeastchris** [comment]
That's a known issue, and caused by floodgate-fabric
https://github.com/GeyserMC/Floodgate-Fabric/issues/59#issue-1304730408
